### ISSUE TITLE
Upgrade to Godot 2.1.5

### ISSUE THREAD

**Issue by fuzzyTew** [w84death/Tanks-of-Freedom#103]
The game works fine on Godot 2.1.5 and docs and projects files should be updated to use it.

I found Godot 2.1.4 to have problems debugging the game, whereas debugging works fine on 2.1.5 .

**Comment by czlowiekimadlo** [comment]
Hey @fuzzyTew thank you for all the tickets and PRs! You might have noticed we don't develop ToF actively anymore, though I might return to it soon. I will look at those PRs and bugs as soon as possible.

**Comment by fuzzyTew** [comment]
Thanks for commenting @czlowiekimadlo .  It's apparent that most of the activity is PR merges; no rush addressing anything.  Are you guys working on anything else cool nowadays?

**Comment by czlowiekimadlo** [comment]
Currently I'm working on our other game Rat is Fat, and w84death is toying with 3D and shaders. You can check out our latest stuff on his twitter https://twitter.com/w84death or mastodon https://mastodon.social/@w84death

**Comment by czlowiekimadlo** [comment]
Latest maintenance release version 0.7.1 has been built with Godot 2.1.6 and it seems to be working. Not that it probably matters anymore :D
