### ISSUE TITLE
F-Droid build fails to install

### ISSUE THREAD

**Issue by kozross** [w84death/Tanks-of-Freedom#11]
Sadly, F-Droid gives me no indication of why. I tried both the 0.3.6 and 0.3.5 builds - same deal.

**Comment by czlowiekimadlo** [comment]
Can you tell me which version of Godot and which OS are you using to do this? We have switched to Godot 1.1 stable a while ago.

Exporting the game from the command line instead of the editor might give some more clues.
Edit:
I remember we encountered similar issue when I tried using toolkit and templates, that I compiled myself. Right now we are using newer versions for development, but 1.1 stable for exports, because game was crashing on all platforms.

One last thing, that caused me to have similar issue, is when I forgot to have same app name, or I used wrong keystore to sign it.

**Comment by kozross** [comment]
My OS is Android Kit-Kat (I can get you the exact ROM if you need to know). As I'm installing from F-Droid, I dunno what version of Godot is being used.

**Comment by czlowiekimadlo** [comment]
Ah, I thought you were compiling the game yourself. F-Droid is not our official build, so if there are any errors in this export, I'm afraid we can't help. 

You could either go to our [our itch.io page](http://w84death.itch.io/tanks-of-freedom) and get latest debug build from there. Or, if you want the app to be verified by Google, you may [sign up for ToF beta on Google Play](https://play.google.com/apps/testing/in.p1x.tof.beta) which will allow you to download our build through Google Play.

**Comment by kozross** [comment]
OK, I tried the itch.io apk, and that wouldn't install either. It gives an error message saying "There was a problem parsing the package."

**Comment by czlowiekimadlo** [comment]
Can you tell me what device are you using? Android version could help, too.

**Comment by kozross** [comment]
The device is a Samsung Galaxy Tab 4 (SM-T530). The Android version is 5.1.1.

**Comment by czlowiekimadlo** [comment]
I remember having similar issues on a borrowed Galaxy Tab, I will try to get it again and see what I can find out.

**Comment by tapir** [comment]
Same issue. 5.1.1 Cyanogenmod. Moto  G 2014. Parsing error.

**Comment by czlowiekimadlo** [comment]
Unfortunately, I do not own any Android device, but I need to have one soon, so I might buy it earlier than planned and debug on it. I intend to buy Galaxy Tab S, don't know how similar it is to Tab 4, but I expect it to be quite close.

**Comment by czlowiekimadlo** [comment]
Have you tried beta sign-up? It is possible, that, for some reason, Android does not like the .apk signed with debug keys.

**Comment by tapir** [comment]
You can use the android emulator. Where do I sign up for the beta? Only place I've seen it mentioned is on the changelog but the link itself I couldn't find.

**Comment by czlowiekimadlo** [comment]
Thanks for the advice, I will try that! Beta signup is here: https://play.google.com/apps/testing/in.p1x.tof.beta

**Comment by tapir** [comment]
it works thanks :+1:

**Comment by kozross** [comment]
I'm gonna wait until you guys fix this in the version available to me either via your website or F-Droid - there's no way in hell I'm going anywhere near a Gulag service. I purged Gapps from my devices _for a reason_.

**Comment by czlowiekimadlo** [comment]
I will share a release-signed version of the apk later today, so you don't have to go through Google Play to get it. I think we should start adding signed versions to itch.io anyway.

**Comment by kozross** [comment]
@czlowiekimadlo That'd be neat. I just wanna play a game where I blow up tanks in turn-based mode. :)

**Comment by czlowiekimadlo** [comment]
Here is a link to download signed version:
https://www.dropbox.com/s/by6exqh9kh6n2g1/ToF_Beta3.6_1280_signed_android64.apk?dl=0

If it does not work, I can only point you to one of the desktop versions, to blow up some tanks while we work out Android issues ;)

**Comment by kozross** [comment]
Nope, that doesn't work either, although now I just get an 'App not installed' message. I guess I'll just wait...

**Comment by czlowiekimadlo** [comment]
I just got Galaxy Tab S with stock Android 5.0.2, game works just fine. Only thing I had to do was to allow apk from unknown sources. Right now I need working tablet, so I will leave it at that, but after Pixel Heaven Expo I will try to install Kitkat and see if it has described issues.

**Comment by czlowiekimadlo** [comment]
Tried reproducing this on Galaxy Tab 10.1 (GT-P7500) with stock software. The game installs, but does not run. I will try to debug this, but it is a bit tricky with dead battery. I will try running the game on 5.1.1 in an emulator and see if I can reproduce this issue.

**Comment by czlowiekimadlo** [comment]
I have installed Android SDK, booted up emulator with 5.1.1, game installs and runs normally. I guess it must be something on your device :(

**Comment by kozross** [comment]
Well damn, that's a pain. Is there any way that I can give you guys some information about why this is happening? I am willing and able to help, but I need a bit of guidance.

**Comment by czlowiekimadlo** [comment]
If you have a machine with Linux, I can guide you on how to get some information from your device. If you only have Windows, it is still possible, but I would rather spare you the pain ;)

**Comment by kozross** [comment]
I have GNU/Linux on all my machines. Guide away.

**Comment by czlowiekimadlo** [comment]
Great!

First, you are going to need adb (Android Debug Tool). This is a standard tool from Google, normally a part of SDK, but luckily, you don't have to get whole bloated SDK, you can install adb separately. For this (and rest of the guide) I assume, that everything is done in terminal.
I'm using Ubuntu, so I just do:
sudo apt-get install android-tools-adb

If you are on different distro, you might have to check for package name, but it should still be easy. With adb installed, you may do:
adb devices
which should show you empty list of available devices. Sometimes starting-up server is needed, there are commands for that:
adb start-server
adb stop-server

Second thing is setting up your device. Here is a step-by-step guide on enabling USB debugging:
http://www.kingoapp.com/root-tutorials/how-to-enable-usb-debugging-mode-on-android-5-lollipop.htm
It boils down to tapping your device ID until hidden menu for developers shows up. Your device should warn you, that this is for developers only. In the dev menu, enable USB debugging (no other options are needed).
When you plug-in the device to your computer, it should ask you if you trust that computer.
If everything went well, when you do again:
adb devices
It should now list your device, and you are ready to go.

We have just published ToF version 0.3.7, signed (release) version for Android is available now on http://w84death.itch.io/tanks-of-freedom so go grab that.

In a Terminal, you might run:
adb logcat
This will print all of the logs, that are available in your device (and will continue doing so, until you Ctr+C). This will show infromation about EVERYTHING that happens on your device (unlocks, taps, apps, etc.) and there is A LOT of it, so I suggest, for the purpose of this debugging, that you don't interact with your device.
When it is done printing all logs, it should start showing a little bit of periodic logs, but it should be small enough to not obscure information, that we want to capture.
TIP: if you never changed your Terminal lines buffer, you might want to increase it.

In a separate Terminal (or tab) we will install the apk:
adb install /path/to/downloaded/file.apk

This normally produces only few lines, but I never had failed install this way, so I don't know exactly what it will show, if it fails. When this command is done, just grab it's output. Also, you should go to the logcat, CTRL+C, and grab any information it produced during attempted install. (there might be a lot)

Please send me results. You might want to use a website, like Pastebin (paste text there, submit, share link), or mail it as txt to me (quak at tlen dot pl)

IMPORTANT: after you are done, go to dev menu on your device, and disable USB debugging, it is not safe to leave it enabled.

**Comment by kozross** [comment]
Well, turns out my issues were a well-known CM bug. You guys had nothing to do with it. Sorry for the huge timesink I made you undertake - your F-Droid build works fine.

**Comment by czlowiekimadlo** [comment]
Not a problem. I hope, that CM community will be able to resolve this, so you can play our game :)
