### ISSUE TITLE
Why there is an arrow above tiles with buildings?

### ISSUE THREAD

**Issue by chomwitt** [w84death/Tanks-of-Freedom#111]
I'm in level 2 of the campaign. 
I select a troop and i use white arrow above tiles with buildings.
But it cant move there.
So what's the point :-) of those arrows?

ps: cool game.

**Comment by czlowiekimadlo** [comment]
White arrow is just a cursor, so you know which tile you are pointing at ;)

**Comment by chomwitt** [comment]
Ok. 
Since it's not correspond to an action maybe there could be a choice for a more subtle UI indication.

ps: still it's cool game. :-)
