### ISSUE TITLE
Website Get Sources section doesn't say to get Godot 2

### ISSUE THREAD

**Issue by Unentokku** [w84death/Tanks-of-Freedom#117]
The instructions on the website are just to download & install Godot from https://godotengine.org/download but that will end up with user getting Godot 3 now which wants a project.godot file when importing but there isn't one.
Might be better to link to https://downloads.tuxfamily.org/godotengine/2.1.6/ or to say to get that version.

**Comment by w84death** [comment]
Thanks for mentioning it. I will update the page.

-------- Original Message --------

**Comment by czlowiekimadlo** [comment]
This information is now in Readme.
