### ISSUE TITLE
Cannot register for online mode

### ISSUE THREAD

**Issue by JPT77** [w84death/Tanks-of-Freedom#126]
I installed tof manually from apk. First time it worked fine. Later I updated to latest version which resulted in tof being installed twice. The new one having no data. Backed up the old data using titanium. 
Well, no idea what's wrong now but i cannot register online any more from the game. Always tells "try later". Regardless if I delete game data.

Thanx

Version 0.7.0

**Comment by czlowiekimadlo** [comment]
Hello and thank you for the report. The issue is with an expired SSL certificate embedded into the game. Recent 0.7.1 release added a new cert that will last until 2035, so online features should work now.
