### ISSUE TITLE
ai freezes

### ISSUE THREAD

**Issue by norill** [w84death/Tanks-of-Freedom#13]
sometimes ai freezes. if auto follow is on it will follow some enemy unit every few seconds over and over again

**Comment by czlowiekimadlo** [comment]
Hello norill, thank you for reporting this issue. We are aware of it. As we just returned from Pixel Heaven, I will now have time to debug this, and we should release this fix soon.

**Comment by czlowiekimadlo** [comment]
Closing this as a duplicate with #16. Should be fixed now in the master branch.
