### ISSUE TITLE
Playability on eink devices

### ISSUE THREAD

**Issue by farooqkz** [w84death/Tanks-of-Freedom#132]
I have tested ToF from F-Droid on my Boox Leaf device which uses an Eink display without color support. I wanted to share my experience:

 - The game is fairly playable. Lack of colors definitely reduces fun of the game but the game is almost playable in X mode(a Eink refresh mode)
 - There is one problem though. It's almost impossible to visually distinguish between red and blue soldiers or vehicles. I suggest an option get added to the game to use Black and White instead of Red and Blue which will make it much better on Eink devices which don't support colours.
 - a photo is attached

![IMG_0016](https://user-images.githubusercontent.com/15038218/219039467-f74a9fec-bb98-4d45-a733-2029c0a269c8.jpg)

**Comment by czlowiekimadlo** [comment]
Wow, that's actually awesome! I'm afraid that the game isn't being actively developed anymore, as I have moved on to ToF II, but If I were to make it more playable on eink, I think it would be better to swap the sprites for one of the sides to a different style, as here we can't rely on colour. Maybe some kind of reduced motion mode as well.

**Comment by farooqkz** [comment]
> 

Thanks for your quick reply :)

Where is the repo for ToF II? I hope it supports more than 2 parties and better multiplayer support(both in LAN and online).
Regarding motions, I don't think further change is required. I will test more later and let you know though.

**Comment by czlowiekimadlo** [comment]
You can find it here https://github.com/P1X-in/Tanks-of-Freedom-3-D and here https://czlowiekimadlo.itch.io/tanks-of-freedom-ii although it is a 3D rather than 2D game, and it will not run on eink for sure. It does allow matches for up to 4 players (team play possible), but at this time there is only hot-seat multiplayer. It already does have online map sharing very similar to the first one (and ToF 1 map import in the editor), and multiplayer is planned later. I am thinking about LAN play, but nothing concrete so far.

**Comment by farooqkz** [comment]
> ...  and it will not run on eink for sure. ...

I beg to differ :)

**Comment by farooqkz** [comment]
Can you provide a production APK for ToF 3D?

**Comment by czlowiekimadlo** [comment]
A Steam Deck can't keep it at 60fps, it barely locks 30fps on bigger maps, so I don't even bother creating an APK 😅

**Comment by farooqkz** [comment]
> 

I highly suggest that you keep the game light. People shouldn't need a powerful GPU to play the game. You could add options to lower graphical details to let the FPS go higher.

Regarding my Eink tablet, it has a SD6xx processor clocked at about 1.1Ghz or 1.2Ghz and has 8 cores. I don't think it would be as bad as you think.

**Comment by czlowiekimadlo** [comment]
If only it was that easy. Godot Engine is not the best performance-wise, and I don't have too much time nor energy to implement elaborate settings for the new game.  It is also aimed at desktop and Deck, so as long as It works fine there and does not burn battery like crazy, then it's good enough for me.

**Comment by farooqkz** [comment]
I'm not much into 3D stuff. But can you use existing Voxel engines perhaps plus some modifications? [Minetest](https://github.com/minetest/minetest) has great performance on even poor hardware.

**Comment by Zireael07** [comment]
@farooqkz Godot's 3D performance isn't the greatest though. Voxel engines often use voxel-specific tricks to get that best perf

**Comment by czlowiekimadlo** [comment]
You are proposing re-writing entire project, which is just my hobby, from ground up, using a different (and unsuitable) engine just for a small chance, that it would work on mobile devices, which was never a goal of the project in the first place. It's not going to happen. ToF II does not use voxels in any way, it just has meshes generated from voxels for aesthetics. That's it. A voxel engine would probably be more of a hindrance than help in this game.

**Comment by farooqkz** [comment]
> 

Please have mercy and don't kill me! I'm not into 3D stuff so I don't know what's suitable and what's not. Also I didn't know the progress had so much progress. However, Minetest performs really well even on mobile.

**Comment by czlowiekimadlo** [comment]
Haha, don't worry, we only bite a little bit :) But yes, ToF II progressed so much, that starting over with a different engine is completely out of the question.

**Comment by farooqkz** [comment]
Since ToF is still works well and is fun. May I ask you to at least change the sprites to black and white and produce an APK? Or is it something I can do myself without too much effort needed?

**Comment by czlowiekimadlo** [comment]
Exporting an APK is fairly easy. Tracking down and converting to grayscale all of the images might be a bit of work though.

**Comment by farooqkz** [comment]
> Exporting an APK is fairly easy. Tracking down and converting to grayscale all of the images might be a bit of work though.

Not all them at once. I think at least Blue/Red must be Black/White instead so that the game will be fairly playable on Eink.

Additional note: Most eink displays support black, white and a number of gray levels. For example my current Eink device as well as the older one which was running Android 6 has got 16 levels of gray plus black and white.
