### ISSUE TITLE
fog flaws

### ISSUE THREAD

**Issue by norill** [w84death/Tanks-of-Freedom#14]
fog sprite looks bad and sometimes structures poke through it. also there should be "hard/black" and "soft/gray" fog for never-seen and not-currently-seen terrain respectively.

**Comment by czlowiekimadlo** [comment]
We are aware of parts of the map poking through clouds, we are fine with it at the moment. We might revise this in the future as possible change though. Same goes for fog style.

**Comment by norill** [comment]
looks like it's mostly fixed with shorter towers
