### ISSUE TITLE
waves flaws

### ISSUE THREAD

**Issue by norill** [w84death/Tanks-of-Freedom#15]
waves could look better and height changes should be more sinusoidal instead of seemingly random

**Comment by czlowiekimadlo** [comment]
The wave movement is actually two different functions colliding. w84death 'tweaked it until it stopped looking like crap', so there is much room for improvement. We should already have this on the board.

**Comment by czlowiekimadlo** [comment]
New update changed the waves a fair bit. Waves may still appear to be random, but should look better... I think :D
