### ISSUE TITLE
Small Resolution Support

### ISSUE THREAD

**Issue by ekianjo** [w84death/Tanks-of-Freedom#20]
Tanks of Freedom has a port on the Open Pandora (not sure if you were aware of it) which is a handheld Linux device. Its screen has a 800*480 pixels resolution and unfortunately in the recent versions of Tanks of Freedom, menu positioning as well as text boxes do not fit well anymore in the screen. 

Could you do something to improve the situation for small screens?  That would be great if you could consider this as you move on with the development.

**Comment by czlowiekimadlo** [comment]
Hi ekianjo. We are aware of the Open Pandora port. Our main target are desktop PCs and hi-res tablets, so we will be developing HUD for them for now. However, it is also an issue on low-res android smartphones. I've been thinking about alternate, simple menus, and we have a task for this on our Trello board.

**Comment by czlowiekimadlo** [comment]
We have just tagged 0.4.0.2-beta version, which addresses many of the low-resolution issues. All menus should work now, there maybe be still some overlap in the workshop though.

I have also posted an update on Pyra and Pandora Forum.

I will close this issue as resolved. If there are still some outstanding low-res problems, please let us know and open a new one :)
