### ISSUE TITLE
keep open the game when multitask view

### ISSUE THREAD

**Issue by moshpirit** [w84death/Tanks-of-Freedom#23]
This is the third time it happens to me: I'm almost going to win the mission 9 (really difficult to me) and accidentally I push the multitasking view button, I select "Tanks of freedom" and I have to start over again.

**Comment by czlowiekimadlo** [comment]
Hi moshpirit,
thank you for reporting this issue. We are aware of it, and I'm afraid we can't do this at the moment. I will have to see if Godot Engine even supports multitasking on android.
That said, we know how annoying this is, as we have encountered this issue multiple times while presenting the game on the tablet. We are developing a save/resume funcionality, so you will be able to start from your last turn, when you accidentally exit the game. It is the last thing we have planned for version 0.4.1, and I hope we will be able to release it in one or two weeks.

**Comment by moshpirit** [comment]
Wonderful news then!! Thanks so much for all your work :)

**Comment by czlowiekimadlo** [comment]
We have just released version 0.4.1-beta, which has Resume, it should solve your problem ;) It is a bit 'experimental', so if you find any issues with resume, please open a new, specific ticket for that issue :)

**Comment by moshpirit** [comment]
Excellent!! ThANK you! ;)
