### ISSUE TITLE
Menus too small at 5" 1080p

### ISSUE THREAD

**Issue by superjamie** [w84death/Tanks-of-Freedom#26]
Try play the game on a 5" 1080p phone like Nexus 5. The menus are too small to read.

The map scales up well, so perhaps scaling could be applied to menus as well?

If you intend the game to be played on a larger screen like a tablet, that's fine, please just list a suggested minimum screen size.

**Comment by czlowiekimadlo** [comment]
Hello @superjamie I'm sorry to hear that. The game should be locked to 720p on Android, we have tested this on a smaller Sony phone, and on Galaxy S5, and it was fine (at least in our opinion). 

Did you get the game from itch.io, Google Play or the F-Droid store? A screenshot of what it looks like on your phone would be also very helpful.

**Comment by czlowiekimadlo** [comment]
I have just tested the F-Droid build and indeed it is not configured properly. If you indeed are using this version, then the only solution I can offer is to use an apk from one of our official channels, which are tof.p1x.in (which links to itch.io), or Google Play beta (link available on itch.io page)

I will contact F-Droid guys and tell them, that their build is not correct.

**Comment by superjamie** [comment]
Thank you!
