### ISSUE TITLE
Translation in french

### ISSUE THREAD

**Issue by Poussinou** [w84death/Tanks-of-Freedom#29]
Hi guys,

Here I am to translate this amazing game in french! :) Just explain the way I have to follow and I will do it with pleasure (If it's not to difficult, I'm new in open source and programming world...) !

So sorry for my bad english, I'm surely not an english native speaker, but I'm able to give a very good translation in french^^

**Comment by czlowiekimadlo** [comment]
Hello Poussinou, we are glad you want to help :) ToF is not really fit for translations right now. We have tried translations provided by the engine in the past, but we were not able to make it work. Now we are using newer version of the engine, so we will revisit this tomorrow and let you know. We also have to figure out a way to switch between languages. In the meantime you may have a look at scripts/translations/tips.gd - it should be a good start.

**Comment by Poussinou** [comment]
I'll go take a look :)

**Comment by Poussinou** [comment]
Some news? :)

**Comment by czlowiekimadlo** [comment]
Wermooz is back on the translations. There are a couple of places where you could add files for French:
translations/
maps/translations
There will probably be more, but that's a start. There is no way to switch the language in-game just yet, but you can probably configure game in your editor to use French... somehow, because I haven't figured that out yet ;) We will have our usual P1X coding session on Wednesday, I will check it then.

**Comment by czlowiekimadlo** [comment]
So far so good, translations seems to be working, there is a lot of work to do though.
You may start by copying translations/translations.csv and maps/translations/campaign.csv to similar .fr.csv files and translating the contents.
Then you can import these to Godot Editor, convert to .fr.xl files, and change in-game language to FR (game_logic.gd::_ready()) and it should work.

If you need more interactive help, you can find me on godot irc or skype.

**Comment by Poussinou** [comment]
I already heard about the Godot Engine but never work with it... So, because I prefer to learn more and more C++ and Linux instead of starting to learn something completely new (I have not too much time to spend on it because IRL I learn chemistry to become engineer), what I can do is translate in french all the files you need and put them here :)

Tell me what you think ;)

PS : is it a problem for the Godot Engine to put more than two " **_,_** " in the text? Because there are two columns, if we write another " , " does it make a third column?

**Comment by w84death** [comment]
Yes, send us the files, we'll do the rest :)

Thanks!

On Wed, Jun 15, 2016 at 10:42 PM, Poussinou notifications@github.com
wrote:

> I already heard about the Godot Engine but never work with it... So,
> because I prefer to learn more and more C++ and Linux instead of starting
> to learn something completely new (I have not too much time to spend on it
> because IRL I learn chemistry to become engineer) so what I can do is
> translate in french all the files you need and put them here :)
> 
> Tell me what you think, the translated files are almost ready ;)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/w84death/Tanks-of-Freedom/issues/29#issuecomment-226313714,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACcr-uiNRRPtyCZM1VtS4WzrlcLmj0nJks5qMGOygaJpZM4IvNGx
> .

## 

Pozdrawiam,
  Krzysztof Jankowski

**Comment by Poussinou** [comment]
[campaign.txt](https://github.com/w84death/Tanks-of-Freedom/files/333179/campaign.txt)
Here is the first translated file with the descriptions of the maps, just rename it campaign.fr.csv

The second one is more difficult to translate, I need some time ^^

**Comment by Poussinou** [comment]
And here is the second one, just rename it translate.fr.csv
[translations.txt](https://github.com/w84death/Tanks-of-Freedom/files/343490/translate.txt)
This translation is fragmentary because some words need a context to be good translated, and some translated words or sentences are maybe too long to be well displayed... So, I need to see the game with the translation in french...

**Comment by czlowiekimadlo** [comment]
Thank you very much for help! We understand, that it may be hard to translate standalone text, so don't worry about it. We are still working on a mechanism to switch languages, and we also have to fix the fonts, as we have removed all non-latin characters, so we will have to bring these back for French.
We were busy going on holidays this week, we are planning to make decent progress on our usual coding session on Wednesday.

**Comment by Poussinou** [comment]
No problem, just ask when it's ready ! ;)

**Comment by LoubiTek** [comment]
Hello !

I too would like to help translate the game in French.
In addition it allows me to see a little more the architecture of a game in Godot.
Besides, I help translate this engine also.

For now I copy the source of the project.
It would good create a list of things to bring to there see clearer.
This will allow to himself share the spots and find out what else needs to be translated.

**Comment by czlowiekimadlo** [comment]
Hi LoubiTek,
we are always glad to get more help :) We will add translations provided by Poussinou to the code, most likely together with scripts to process them, and some documentation on how to use this. You may expect this to be available this week.

As for the game architecture, ToF is our first Godot project ever, so it might not be the best :D Feel free to look around the code, I hope you will find it helpful regardless :D

**Comment by czlowiekimadlo** [comment]
@Poussinou I have added your translation to the game, however we still have to restore non-latin chars to the font, otherwise things like 'É' will not show up. And we have to modify many in-game labels to be translated.

**Comment by Poussinou** [comment]
@LoubiTek Salut, on peut se coordonner comme tu veux pour traduire le jeu, comme dit, certains mots n'auront pas la place d'être affichés en entier, et la traduction n'est pas finie... On se relit mutuellement? :)

@czlowiekimadlo So, I remove all the É, é, à, À... in the french translation (and I add some new translations) ?

**Comment by czlowiekimadlo** [comment]
@Poussinou no need, w84death will fix the font so it will be ok, It's just that they are missing right now, so don't get alarmed if translations look messed up :)

**Comment by Poussinou** [comment]
ok ;)

**Comment by Poussinou** [comment]
Can you create a new repo for the description of tanks of freedom in the google play store, or a new folder in this repo. I don't know if there are some key words in the google store description of ToF, but it's very usefull (I was looking for ToF in the google play store using the keyword "tanks" but I could not find it:( ), so if it's not the case, I can add it, and translate the description in french;)

Do you know how to add a software in the ubuntu software too? Maybe you can add it?

**Comment by czlowiekimadlo** [comment]
We are still working on applying translations we have. Game can't be found in the Google Play because it is not released yet - only available with beta invite. Adding anything to official Ubuntu repository is not that straightforward and I'm afraid we are a bit lazy :D Our friends from Godot community added ToF to Mageia repository though.

**Comment by Poussinou** [comment]
OK for the translations in the Google play store, we will do it later;)

I found the way to install ToF using the play store. If you search "P1X" in the store, you can see the ToF app in early access, and you can install it, beta-invite or no. I don't know if it's a bug? I have no beta-invite for example, but ToF is installed via the play store on my phone... That's why, I was asking for a translation of the description, but no problem, I can do it later;)
For the Ubuntu software center, maybe one day! ;)

**Comment by czlowiekimadlo** [comment]
Maybe Google Play is changing its functions with early access being popular nowadays. Thank you for the update! Right now we are working to cover whole game with translations, while waiting for new engine release, that will make non-latin characters work. Expect some more translation keys ;)

As for Ubuntu software center, we haven't thought of that, but we have plans for Steam, so the game would be available for Ubuntu through that. After that I might look at packaging policies.

**Comment by Poussinou** [comment]
Yes, I think that's why we can install ToF through Google Play
No problem for the update ;) Have you ask for a new Godot Engine release supporting non-latin characters yourself? Anyway, the whole game in french (or polish) will be amazing!

Steam is the best way to publish ToF I think, and yes it must be easier than the official Ubuntu software center x)
When it will be available on greenlight, I would do some advertising if you want, through friends and groups ;) (https://steamcommunity.com/groups/IG4eva or http://steamcommunity.com/groups/indius for exemple) you also can do it yourself, but because I'm very enthusiastic I can do it for you ^^"

**Comment by czlowiekimadlo** [comment]
We didn't have to ask - better font handling was needed anyway, and better support for translations is more of a side-effect of that.

As for publishing, we will greatly appreciate any and all help! Although it might be a topic for another thread ;)

**Comment by Poussinou** [comment]
Yep big topic for another thread ;)

Is there a place where I can submit some ideas?

**Comment by czlowiekimadlo** [comment]
Not really. You could open new issue and indicate it is a feature request or something like that.

As for translations, today we have mostly finished the translations. We have ported to 2.1 and filled english files with all the labels. I have copied them to other languages. Current plan is to release new version as soon as we can. There are only a couple of fixes left. If you could manage to update FR translations it would be awesome, but it is not a blocker - we will release even with incomplete translations and improve over time.

If you have the project cloned and running in Godot 2.1, then, after you update FR files, open a terminal in project root and run bin/compacty.py using Python 3. This will build translations for you, and if you run the game from editor, it will build .xl files as well. You can add all modified files in translations folder to the PR. After new release I will check if we can omit commiting .xl files to the repository, as it seems the editor will rebuild them anyway (a big improvement over previous behaviour)

Thanks for help @Poussinou !

**Comment by Poussinou** [comment]
I can upload the translations in french tomorrow on Thursday, in the beginning of the afternoon ;)
I do not run Godot Engine at all, so I cannot build any .xl files, but i will merge a pull request as soon as possible, ok for you?:) I don't know how Godot Engine works... Maybe one day I will learn it;)

**Comment by czlowiekimadlo** [comment]
Sure, that's fine.

Using Godot is very easy - if you are using Windows, it is way easier than using git for creating pull requests :D You just download a binary for your system (windows, linux, osx) from godot website, run it and import the project. You don't even have to install it.

One important thing: we have now a character limit for labels. Any translation key starting with LABEL_ will be a subject to this limit, which is 20 characters. That said, many labels in the game need to be even shorter. Currently, many FR translations are just too long. You can download windows version here to check it: https://www.dropbox.com/s/t7y2wexpstn3tw5/ToF_Beta_0.5.1_win64.exe?dl=0

**Comment by Poussinou** [comment]
First I'll translate the files, later I will make a new pull request to resolve the problem of too-long-translated-words using the 0.5.1 beta;)

I will have a look to Godot later, no time today :S

**Comment by Poussinou** [comment]
I'm currently working with the 0.5.1 opened, to see which translations are too long...

**Comment by czlowiekimadlo** [comment]
Version 0.5.1 is live. Thank you all for your awesome help in bringing french language to ToF!

I will close this ticket. Please open a new one if you find any issues, or just make a pull request.

**Comment by czlowiekimadlo** [comment]
I have just created ticket #43 which is meant as a thread to update translation contributors about new releases, that need new translations. Please join if you are interested ;)
