### ISSUE TITLE
campagin 13 "crash site"

### ISSUE THREAD

**Issue by trenkert** [w84death/Tanks-of-Freedom#30]

**Comment by czlowiekimadlo** [comment]
Hello trenkert,
sorry to hear you are having trouble with this mission. We are playtesting the campaign every time we make a game balance change to make sure it is still beatable. Current version has been even tested on kids, and seemed ok. 
You can try switching mission difficulty from Normal to Easy, button is on the mission selection screen. Hope that helps!
