### ISSUE TITLE
Missing tip

### ISSUE THREAD

**Issue by coppolaemilio** [w84death/Tanks-of-Freedom#34]
There is an error on one of the tips before each turn. Here is an image:
![screen shot 2016-08-18 at 1 29 12 am](https://cloud.githubusercontent.com/assets/2206700/17807293/d9ad0ac6-6609-11e6-86a1-413155f9eee0.png)

**Comment by czlowiekimadlo** [comment]
Thank you for the report, this is already fixed and will be available in the 0.5.1 release.
