### ISSUE TITLE
Translation fail

### ISSUE THREAD

**Issue by Poussinou** [w84death/Tanks-of-Freedom#35]
Only labels appear in the android version of the game 0.5.1

**Comment by czlowiekimadlo** [comment]
Hmm, that's odd. I will check other versions while my tablet is charging.

**Comment by czlowiekimadlo** [comment]
Hmm, that's odd. I will check other versions while my tablet is charging.

Windows version appears to be fine, aside from a couple of button labels we forgot to fix. I will wait for tablet to charge up and check.

**Comment by Poussinou** [comment]
Here is a screen-shot of the game running on my phone, android 5.1
![screenshot_2016-08-20-22-57-38](https://cloud.githubusercontent.com/assets/19646549/17833934/98c9482a-672c-11e6-80e5-5cf93c4ea231.png)

The game is running perfectly on my ubuntu 16.04, no problem with labels, and it's also running on windows (via wine), seems like the only problematic platform is android^^

**Comment by czlowiekimadlo** [comment]
Engine for the android platform was missing translations import. Can you test this file:
https://www.dropbox.com/s/cj4y3981804enm3/ToF_Beta_0.5.1_signed_android64.apk?dl=0
before I upload it to itch?

**Comment by czlowiekimadlo** [comment]
Ok, tested it on my tablet and it works, so publishing.

**Comment by czlowiekimadlo** [comment]
Please re-test when you can and close if everything is ok.

**Comment by Poussinou** [comment]
It's working for me too! ;)
