### ISSUE TITLE
Deploy button

### ISSUE THREAD

**Issue by Jerzeydan** [w84death/Tanks-of-Freedom#42]
When creating new units, the deploy button doesnt work all the time / is hard to hit

**Comment by czlowiekimadlo** [comment]
When spawn point is occupied by a unit, you will not be able to deploy new one - maybe that is your issue. We have to add information about that to the UI, so people know that.

**Comment by Jerzeydan** [comment]
That is not my issue. I meant that sometimes when I try to tap the deploy- button, the map square underneath the button is selected instead.

**Comment by czlowiekimadlo** [comment]
Ah, then I know where the problem is. Can you tell me which platform are you using? If it is desktop PC, are you using fullscreen?

**Comment by Jerzeydan** [comment]
Ah, sorry. I forgot to mention.. I'm playing on Android. Phone is Nexus 6p and android version 7.0

**Comment by czlowiekimadlo** [comment]
Hmm, I don't have that issue on my Galaxy tablet, are you using apk from itch.io/Google Play or F-Droid?

**Comment by Jerzeydan** [comment]
Google play

**Comment by czlowiekimadlo** [comment]
I'll try to reproduce this issue with my device.

**Comment by czlowiekimadlo** [comment]
I'm only able to reproduce this while hitting very edge of the button. Overall, on my tablet, it's ok. I'll have to check on a phone, maybe smaller screen makes the button harder to hit.

**Comment by czlowiekimadlo** [comment]
After playing some games on my PC I have noticed, that there is some issue with bottom half of the Deploy button bleeding clicks to the map underneath. I'll fix that for 0.6.0-beta and we will see if that helps.

**Comment by czlowiekimadlo** [comment]
I just noticed, that android build has overscan allowed - it should not. Please check in game options if you have overscan enabled. If yes, then please turn it off, load a new map and see if issue is still there.

**Comment by cyberbeat** [comment]
I had the same problem, it was nearly impossible to hit the deploy button (samsung galaxy s4 mini with cyanogenmod 13 and this game latest release from f-droid store).

Turning off overscan resolved the problem.

**Comment by Jerzeydan** [comment]
Disabling overscan fixed the issue! Why the android version even has it?

**Comment by czlowiekimadlo** [comment]
It's an oversight with the build configuration - it should not be there. I have already removed it in the master branch, next release will not have that option available.

**Comment by czlowiekimadlo** [comment]
Next ToF version, which should be released this month, will have this fixed, so I'm closing this ticket.

**Comment by cyberbeat** [comment]
Thanks!
