### ISSUE TITLE
[new feature] Possibility to change the flag in multiplayer

### ISSUE THREAD

**Issue by Poussinou** [w84death/Tanks-of-Freedom#47]
Add the possibility to change the flag and to choose one. Here is an example I did quickly using Kolourpaint (Poland guys ;) )
Made without the colour pallet you use for ToF, but I can fix this problem^^
![flag_poland](https://cloud.githubusercontent.com/assets/19646549/20249619/6c313a48-a9fd-11e6-9ec3-bb9a3a0cbef4.png)

**Comment by czlowiekimadlo** [comment]
Hmm, we could add more flags to the game when we introduce scripting (for campaign story purposes). In multiplayer we would have to add separate setup screen, then we could add more options, including flags.

**Comment by Poussinou** [comment]
Ok if one day, you want to implement this option, ask me for flags if you want
