### ISSUE TITLE
[new feature] Preview the maps in the map-selection pages

### ISSUE THREAD

**Issue by Shayan-To** [w84death/Tanks-of-Freedom#51]
A small thumbnail of how the map looks like so that one doesn't have to open them one-by-one to just see how big they are...

**Comment by czlowiekimadlo** [comment]
We do have this on the roadmap, so we will do this in future. It is scheduled for versions 0.8.x.

**Comment by czlowiekimadlo** [comment]
This feature is already available in ToF 2.
