### ISSUE TITLE
[new feature] Add 3, 4, or more number of players support

### ISSUE THREAD

**Issue by Shayan-To** [w84death/Tanks-of-Freedom#55]
It will be possible with the current game dynamics I think. And as the game is turn-based, multiplayer will work the same way.

**Comment by moshpirit** [comment]
Wouldn't this be very unfair to player 4? All players moved before, so they probably have more money and more probability to kill player's 4 army

**Comment by Shayan-To** [comment]
The money is given at the end of the turn, so no one has more money than any other. And if the bases of the players are not too close to each other, then there is no obvious advantage for anyone.

**Comment by czlowiekimadlo** [comment]
Hello and thanks for feedback! AP is actually given at the start of the turn, not at the end. Not that it makes much difference. This feature is now available in ToF 2 early builds on itch. I have not tought about the last player being at a disadvantage in this situation, although it can be counteracted by giving the last player some additional AP boost in their first turn.
