### ISSUE TITLE
Idea: Buffs

### ISSUE THREAD

**Issue by phrohdoh** [w84death/Tanks-of-Freedom#57]
For example a capturable hospital structure could:
  * heal infantry by 1hp per turn across the board, or
  * heal infantry within a 3-cell proximity 1hp per turn,
  * ...

The same could be done for vehicles (or there could be no distinction between human and machine, just a single structure/entity providing a proximity-based buff)

This could of course be done for damage and health/defense, etc.

If any of this is of interest to the team let me know, I'd like to spend some time implementing this if it is desired.

Do you guys have an IRC channel, Slack, etc?

**Comment by czlowiekimadlo** [comment]
Hey ;) Thanks for the ideas!
We already thought about that, but for now we view units as balanced enough, and throw-away aspect of them is not an issue for us right now. We plan to make more interesting campaign next, and new units, buildings and gameplay mechanics may come later.

Game is open source, so feel free to implement it and see how it works out!
We do not have our own IRC, but I tend to hang around GodotEngine IRC and Discord channels.

**Comment by czlowiekimadlo** [comment]
ToF 2 is now available on itch and it does have buffs that come from certain hero abilities.
