### ISSUE TITLE
What about factories/mines/offices?

### ISSUE THREAD

**Issue by thesisek** [w84death/Tanks-of-Freedom#58]
This will help you in balance. Radio should be the second-order money source, sholdnt it?. When you add this, it will be common money producer. But if you add this, radio must lost some profit. Write me if you like my idea

**Comment by czlowiekimadlo** [comment]
Hello and thank you for your feedback. This was actually already (somewhat) the case in game, as HQ and Airfield buildings also provide AP. In recently released ToF 2 now all production buildings provide some amount of AP, though Towers are still the main source. Adding even more sources would need a total rebalance, as right now the money is too abundant in late game when player controls most of the buildings on the map.

That being said, the game is open-source, so you are free to experiment and discuss results!
