### ISSUE TITLE
ToF not working on Android N

### ISSUE THREAD

**Issue by ghost** [w84death/Tanks-of-Freedom#64]
I have played this in the past, when I was still on Lollipop I think, and it worked fine and was one of my favourite pass times. However, now when I press campaign it shows me the main menu but without the background (so I press campaign, then start, then it takes me back to the main menu (with settings, demo, quit,...) but without the background). If you want, I can attach catlogs (in fact, I'll do that asap)

**Comment by czlowiekimadlo** [comment]
Hey Matttter, thank you for the report. Your issue sounds a bit like the one we had with 0.6.1, so please make sure you updated the game to at least version 0.6.2. We actually released 0.6.3 this week btw. 

If it occurs on the latest build, then it might be a problem. We haven't tested the game on Android 7 (not sure if my Galaxy Tab S will even get that), so there may be some issues. Catlog will be very helpful.

**Comment by ghost** [comment]
So, I'm sorry to have probably wasted your time, I was running the
latest f-droid build (which is indeed 0.6.1). I will upload the catlog
anyway, even if you probably have already resolved the issue. Thanks for
your reply

**Comment by ghost** [comment]
[device_info.txt](https://github.com/w84death/Tanks-of-Freedom/files/850595/device_info.txt)
[logcat.txt](https://github.com/w84death/Tanks-of-Freedom/files/850594/logcat.txt)

**Comment by czlowiekimadlo** [comment]
Hi, I just managed to get my hands on an Android 7.0 tablet and the latest Play Store build works just fine. F-Droid is not our official distribution channel, so you probably have to report F-Droid guys, that they have outdated version.

**Comment by czlowiekimadlo** [comment]
Logcat confirms it is indeed the 0.6.1 known issue 

> 03-17 09:40:24.707 I/godot   (2876): [1;35mSCRIPT ERROR: load_map: [0m[1mInvalid get index of type 'Nil' (on base: 'Nil').
> 03-17 09:40:24.707 I/godot   (2876): [0;35m   At: res://scripts/game_logic.gdc:178.[0m
