### ISSUE TITLE
You completly stopped updating the game

### ISSUE THREAD

**Issue by thesisek** [w84death/Tanks-of-Freedom#72]
Where is the promised major update? Include some advert in game to earn money. Then spend this money on the advertising of this game. There will be more players here. Add open and colsed-source tournaments, 20% leaving for yourself. I have written this beacause I trust u.

**Comment by czlowiekimadlo** [comment]
Please post only tickets that are either bug reports or feature requests.

ToF being a hobby project, we are not bound by any deadlines. We haven't stopped working on it though. Adding ads is out of the question, our games will always be ad-free.

**Comment by Poussinou** [comment]
Keep up this good work guys, I love your AD-FREE game, do not pay attention to this kind of people <3
