### ISSUE TITLE
how to add translations?

### ISSUE THREAD

**Issue by thamer898** [w84death/Tanks-of-Freedom#81]
Hello

How to add translations for this game like rtl languages ( arabic ) ?

thanks in advance .

Regards

**Comment by czlowiekimadlo** [comment]
Hi,

all information about translating the game is contained here: https://github.com/w84death/Tanks-of-Freedom/blob/master/TRANSLATIONS.md
That said, we never made the game with RTL in mind, and I don't know if Godot Engine supports that, so I don't know if this is even possible for ToF.

**Comment by thamer898** [comment]
Thank you very much i will try it and inform you about the results
