### ISSUE TITLE
Error when try to play online at the moment of registering player id

### ISSUE THREAD

**Issue by haxpor** [w84death/Tanks-of-Freedom#83]
I tested on both iOS and Android, only relevant error log for both is as follows.
I built and tested with Godot 2.1.4 stable official release

**iOS 11.2.5**
```
...
[1;31mERROR: _print_error: [0m[1mA failure in the SSL library occurred, usually a protocol error.
[0;31m   At: modules/openssl/stream_peer_openssl.cpp:418.[0m
...
```

**Android 6.0**
```
...
01-08 04:42:18.413 31030 31065 I godot   : ERROR: queue_delete: Condition ' !is_inside_tree() ' is true.
01-08 04:42:18.413 31030 31065 I godot   :    At: scene/main/node.cpp:1978.
01-08 04:42:18.415 31030 31532 I godot   : ERROR: connect: Condition ' !p_host.is_valid() ' is true. returned: ERR_INVALID_PARAMETER
01-08 04:42:18.415 31030 31532 I godot   :    At: drivers/unix/stream_peer_tcp_posix.cpp:140.
...
```

**Comment by czlowiekimadlo** [comment]
Thank you for the report. I'll look into the android version when I get home. We never made an iOS build, so I can't guarantee it will work.

Is this an official android build? Or a custom one?

**Comment by haxpor** [comment]
Alright. I build against 48ca879.

**Comment by czlowiekimadlo** [comment]
I have tested this commit on my Linux box, and it seems to be working. Your error indicates some issue with the configuration, so it fails to connect. Still, this should result in an in-game error popup that would return you to the main menu, not a crash.

Looking at the engine.cfg file, I can see a slight difference between 'development' engine config, and the one we use for exports. Are you using default configs, or the ones from buildConfig folder? Default one seems to be working just fine on Linux, though maybe it is somehow bad for mobile systems.

Also, could you try registering with the APK from Itch.io, Play Store or the F-Droid? As these should be working.

**Comment by haxpor** [comment]
Thank you for your fast reply!

Indeed, I checked by downloading an official build from itch.io, and it works fine.
Apology, for issue above, tested it again, it didn't crash but show error.

I notice difference as I now believe I use default `engine.cfg` so UI are small on Android for custom build. But on official build, its size is proper and not small like former.

How can I change `engine.cfg` to use one for Android?
 
**PS**: After this I will test on iOS for you guys again as well.

**Comment by czlowiekimadlo** [comment]
Glad to hear it works as expected.

You can either manually copy the `buildConfig/engine_android.cfg` file as `engine.cfg`, or use a provided script - please see https://github.com/w84death/Tanks-of-Freedom/blob/master/PORT.md at the bottom is Export Scripts section.
The command is:
`./bin/export bootstrap android`

though that will complain for a missing export config. There is a .dist you can use to make it work.
That makes me think it might be an issue with the export file - default export config might be missing permission to use internet, so I further advise to use that .dist.

And last but not least, the master branch is currently presenting itself to the server as version 0.7.0, but  the server will not accept it. I will add 0.7.0 to the accepted list closer to the release of that version. Alternatively, you can build the 0.6.3 tag, that is the currently released version.

**Comment by haxpor** [comment]
Thanks. I close this now as it should not be a problem when 0.7.0 is ready later.
