### ISSUE TITLE
Missing project.godot ...?

### ISSUE THREAD

**Issue by hoijui** [w84death/Tanks-of-Freedom#89]
I suppose i am doing something wrong, but when i download latest Godot engine (3.0.1.stable.official) and run it, and i click on "Import", it wants me to open a _project.godot_ file. There is no such file in the Tanks-f-Freedom repo.

**Comment by czlowiekimadlo** [comment]
Hi hoijui, ToF is a Godot 2.1.4 project, we are yet to port it to 3.x, but this might never happen due to amount of work needed and lack of new features, that would be useful in this game.

**Comment by hoijui** [comment]
ahh i see, thanks!
don't ask me how i could over-read that in the README... ;-)
