### ISSUE TITLE
Android package name

### ISSUE THREAD

**Issue by goshki** [w84death/Tanks-of-Freedom#9]
I know the game is not in Google Play or anything so just a heads-up that [this package name](https://github.com/w84death/Tanks-of-Freedom/blob/c6125d7eb20ec2c7f67e2a8246880b13782b52f9/buildConfig/export_desktop.cfg#L30) does not look too good. ;-)

**Comment by czlowiekimadlo** [comment]
This config file is for desktop builds only (Windows, Linux, OSX). For android we have [separate export ](https://github.com/w84death/Tanks-of-Freedom/blob/master/buildConfig/export_android.cfg.dist) which requires release keystore configuration to work from command line.

**Comment by goshki** [comment]
Ok, then I must have installed some old version (1.0) because in the logs it says package name is "com.android.noname". No problem then! :-)
