### ISSUE TITLE
Bug with calling of the character

### ISSUE THREAD

**Issue by dararc** [w84death/Tanks-of-Freedom#91]
Hello, I have found a problem when my unit rises in the field where the enemy unit has to be called, and I finish the course, a game breaks.

Hello, I have found a problem when my unit rises in the field where the enemy unit has to be called, and I finish the course, a game breaks.

Sorry for my english, i don't know it wery well (-_-)

**Comment by czlowiekimadlo** [comment]
Thank you for the report, though I'm afraid I don't understand when the crash occurs.

**Comment by dararc** [comment]
Forget, I all over again rechecked, an error not in it.

**Comment by dararc** [comment]
You can delete this issue
